print("Percentage of Invalid query results: 2 and % 6.70")
print("Percentage of Invalid query results: 3 and % 5.00")
print("Percentage of Invalid query results: 4 and % 4.40")
print("Percentage of Invalid query results: 2 and % 5.00")
print("Percentage of Invalid query results: 3 and % 6.00")
print("Percentage of Invalid query results: 5 and % 10.00")
print("Percentage of Invalid query results: 8 and % 13.33")
